### ISSUE TITLE
Original error: The Content-MD5 you specified is invalid for multi-part uploads.

### ISSUE THREAD

**Issue by niradler** [denis-fatkhudinov/s3-redeploy#1]
any idea ?

**Comment by btrdnch** [comment]
Hi @niradler, 
could you supply command line parameters you used?

**Comment by niradler** [comment]
npx s3-redeploy --bucket xxx --cwd ./build --cf-dist-id xxx

**Comment by btrdnch** [comment]
Hey @niradler 
Tested on my machine, works just fine. 
Ran on:
* Windows `npm: 6.4.1` and `node.js: 10.15.3`
* Windows `npm: 5.6.0` and `node.js: 8.5.1`
* Ubuntu `npm: 6.4.1` and `node.js: 10.15.1`

Could you please share details from your side?
* What's OS, node and npm versions?
* Could you run the same command using another `--cwd`? The goal is to have a sample `.txt` file with `Hello world` inside.

**Comment by btrdnch** [comment]
Hey @niradler 
Do you have any updates?
Keen on getting this reproduced on my side and eventually resolved

**Comment by niradler** [comment]
Sorry I moved to aws cli we can close this

**Comment by matthewrobb** [comment]
I am also running into this as of this morning

**Comment by btrdnch** [comment]
Hey @matthewrobb 
Could you please share you system / node info and a list of actions that lead to this issue so I could reproduce on my side?
