### ISSUE TITLE
Target directory

### ISSUE THREAD

**Issue by bassomatic32** [denis-fatkhudinov/s3-redeploy#3]
Is it possible to target a specific target folder in the specified bucket?

**Comment by btrdnch** [comment]
Hey, with the current functionality you can do the following:
* Let's say you have a bucket `bucket-name`
* Let's say you have a folder `your-bucket-folder` in the bucket 
* Create a `your-bucket-folder` locally. Let's say `parent-folder/your-bucket-folder` in your file system
* Now if you run `npx s3-redeploy --bucket bucket-name --cwd ./parent-folder --no-rm --no-map`, contents of `your-bucket-folder` will be uploaded to the bucket under `your-bucket-folder` folder. In addition to `cwd`, you can use the `pattern` cmd parameter.

Note: `--no-rm` flag means no files will be removed from the bucket at all, so your local files will be uploaded in addition to already existing ones.

**Comment by bassomatic32** [comment]
I appreciate the reply.  I'll look into this.

**Comment by btrdnch** [comment]
Hey @bassomatic32 
Have you resolved your issue so far?

**Comment by btrdnch** [comment]
Closing as there was no reply. Feel free to open another issue or add comments here.
